### ISSUE TITLE
IPN is not consistently passing along the "number" value in its "invoice_number" field

### ISSUE THREAD

**Issue by jcorning99** [paypal/here-sideloader-api-samples#31] opened 2015-09-08 14:00 UTC
I am using the PayPal Here Sideloader API to integrate PayPal Here with my web-based software for Boy Scout and Girl Scout troops.

In testing the interface I discovered that the "number" value that I passed to PayPal Here would be returned as the "invoice_number" field on the Instant Payment Notification (IPN).   This gave me exactly what I needed to identify the original transaction so I could post the completed payment.

I have made this function available to my customers, one of whom is reporting a problem with completed payments posting properly.  I have tracked this down to the failure to pass through the "number" value to the "invoice_number" in the IPN.

To verify this, I altered our software temporarily to display the complete string that we pass to PayPal Here right before we pass control.  This clearly shows our reference number in the "number" field as "Merch.1220.25.1".  

The corresponding IPN message had a value of "0005" in the "invoice_number" field.  This appears to be a sequential number that increments on every subsequent payment.

Is this controlled by a configuration setting, either in the customer's PayPal account or in the PayPal Here software?

How can I guarantee that the "number" value will get passed through to the "invoice_number" field in the IPN?

**Comment by jaredegan** [comment] 2015-09-08 14:15
@jcorning99, some questions:

Main question:
- Can you ensure that the the "Merch.1220.25.1" type values are unique when you pass them? I believe if you pass our invoicing service a number that has already been used, it will come up with it's own, and start auto-incrementing. This is the best guess I have right now. I would guess that "Merch.1220.25.1" has been passed through 4 or 5 times, which is why you're ending up with "5". The number value must be unique.

Other questions:
- Is this happening on iOS, Android or both platforms?
- Have you seen other reference numbers formatted like "Merch.1220.25.1" successfully go through?
- You say you have seen this work. Does this happen intermittently, or is it consistent for one particular customer?

**Comment by jcorning99** [comment] 2015-09-08 14:34
Jared,

 

Thank you for responding so quickly.

 

I can guarantee that the "Merch.1220.25.1" type values are unique, not only for the current users but across all users of our application.   Before we pass control to PayPal Here we insert a record into our database with the details of this specific order.  The “25” in the example is the identity key value of this record.  The next order they process will have a new identity key value.  The “1220” identifies this particular subscriber, which ensures that the entire string is always unique.

 

This particular test was using iOS on an iPhone5, using a copy of PayPal Here that was installed yesterday.

 

This pass through worked consistently for me in my testing, both on iOS and Android.  I recreated this result yesterday on my iPad running iOS 8.4.1 using PayPal Here version 2.5.1 (251000).  In every case, the value I supplied in the “number” field was included in the IPN message in the “invoice_number” field.

 

For the customer  who is having the problem, I’ve seen a series of IPN messages from their testing that contain a four digit sequential number in the “invoice_number” field, e.g. “0001”, then “0002”, etc.  This is consistent for this customer.

 

Please let me know if there is anything I can do to help you track this down.

 

Regards,

 

 

 

John

**Comment by jaredegan** [comment] 2015-09-08 16:42
This seems very much like an integration issue, not a bug with PPH. Am I right to assume you built the system the customer is using? Are you hosting it? How does it differ from the system you used to successfully test this?

We don't have any sort of logs we can check on our side. Could you get us the URL that triggers the PPH app to open?

**Comment by jcorning99** [comment] 2015-09-08 17:41
Jared,

 

The customer is using the same software on the same server that I used for my testing.  You can run it yourself at https://www.TroopWebHost.org/TroopABC.  Log on as user “demo” with a password of “demo”.

 

Once you’ve logged on, find the “Sales” menu and select “Booth Sales”.  Select the existing booth and click on a product to create an order, then click the “Card” button to initiate PayPal Here.

 

I’ve attached a screenshot that our customer sent us that displayed the URL that triggered PPH during her unsuccessful test.

 

Here is the URL that was generated when I ran a test of this interface from the same software on the same server:  

paypalhere://takePayment?returnUrl=https%3A%2F%2Fwww.TroopWebHost.org%2FSalesBoothReturn.aspx%3FType%3D%7BType%7D%26Number%3D%7BNumber%7D%26Tip%3D%7BTip%7D%26Email%3D%7BEmail%7D%26TxId%3D%7BTxId%7D%26GrandTotal%3D%7BGrandTotal%7D&accepted=card&step=choosePayment&invoice=%7B%22itemList%22%3A%7B%22item%22%3A%5B%7B%22name%22%3A%22Bacon%20Ranch%22%2C%22quantity%22%3A1%2C%22unitPrice%22%3A%2220.00%22%2C%22taxRate%22%3A%220.0%22%2C%22taxName%22%3A%22Tax%22%7D%5D%7D%2C%22paymentTerms%22%3A%22DueOnReceipt%22%2C%22currencyCode%22%3A%22USD%22%2C%22number%22%3A%22Merch.10.10.229%22%2C%22discountPercent%22%3A%220%22%2C%22merchantEmail%22%3A%22%22%7D

 

Thanks for continuing to research this issue.  I’ll do everything I can to help.  We need to get this to work.

 

Regards,

 

 

John

**Comment by jaredegan** [comment] 2015-09-08 18:35
@jcorning99 Alright, it does indeed seem to be a PPH bug. Good find.

It seems that if tips are enabled, the process of setting the tip clears the number value, which the server than fills in on its own with its auto-incrementing values. So I'm guessing in your tests, you had Tips off, and this customer has Tips on.

Please instruct the user to turn off tips in PPH and give it another try. Please let me know the result. I'll get this bug fixed in 2.6, which is targeted for going live in early October.

**Comment by jcorning99** [comment] 2015-09-08 22:13
Jared,

 

Thank you for tracking this down so quickly.  I will advise my customers to turn off tips.

 

Regards,

 

 

John

**Comment by jaredegan** [comment] 2015-09-09 21:01
@jcorning99 Any news from the user?

**Comment by jcorning99** [comment] 2015-09-09 21:44
Jared,

 

Yes, the user turned off tips and the completed payment successfully posted via IPN.

 

Thanks again for figuring this out.

 

Regards,

 

 

John

**Comment by jaredegan** [comment] 2015-09-14 16:40
This fix will be live in version 2.6, shipping early October.

In the meantime, the confirmed workaround is to disable tips.

**Closed by jaredegan** 2015-09-14 16:40 UTC
Labels: bug, ios
